minor fix

diff --git a/stack-compute-aws-demo/pipeline/pipeline.yml b/stack-compute-aws-demo/pipeline/pipeline.yml
--- a/stack-compute-aws-demo/pipeline/pipeline.yml
+++ b/stack-compute-aws-demo/pipeline/pipeline.yml
@@ -123,7 +123,7 @@ jobs:
           passed:
             - deploy
 
-      - task: install-applications
+      - task: get-kubeconfig
         config:
           platform: linux
           image_resource:
@@ -136,58 +136,34 @@ jobs:
             args:
               - '-c'
               - |
-                export INSTANCE_ID=$(cat tfstate/metadata | jq -r .instance_id)
-                export INSTANCE_PUBLIC_IP=$(aws ec2 describe-instances --instance-ids ${INSTANCE_ID} --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
-                echo $INSTANCE_PUBLIC_IP
-                export AWS_ACCESS_KEY_ID=$(echo ${CY_AWS_CRED} | jq -r .access_key)
-                export AWS_SECRET_ACCESS_KEY=$(echo ${CY_AWS_CRED} | jq -r .secret_key)
-                export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
-                export TERM=xterm
-                CMD_ID=$(aws ssm send-command \
-                  --instance-ids "${INSTANCE_ID}" \
-                  --document-name 'AWS-RunShellScript' \
-                  --parameters commands="\"
-                    curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE='644' INSTALL_K3S_EXEC='--disable traefik --disable servicelb --tls-san ${INSTANCE_PUBLIC_IP}' sh -s -
-                    until sudo ls /etc/rancher/k3s/k3s.yaml >/dev/null; do sleep 1; done
-                    sudo mkdir -p /home/admin/.kube
-                    sudo cp /etc/rancher/k3s/k3s.yaml /home/admin/.kube/config
-                    sudo chmod 644 /home/admin/.kube/config
-                    sudo cp /etc/rancher/k3s/k3s.yaml /home/admin/.kube/public_ip_config
-                    sudo sed -i "s/127.0.0.1/${INSTANCE_PUBLIC_IP}/" /home/admin/.kube/public_ip_config
-                    sudo chmod 644 /home/admin/.kube/public_ip_config
-                    cd /tmp
-                    curl -sL https://get.helm.sh/helm-v3.17.1-linux-amd64.tar.gz | tar -xvz
-                    sudo mv linux-amd64/helm /usr/bin/helm
-                    sudo chmod +x /usr/bin/helm
-                    rm -rf linux-amd64
-                    helm upgrade --set controller.hostPort.enabled=true --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace
-                    kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
-                  \"" \
-                  --comment "Install K3s" | jq -r '.Command.CommandId')
-                until [ $(aws ssm get-command-invocation --instance-id "${INSTANCE_ID}" --command-id "${CMD_ID}" --query 'Status' --output text) != "InProgress" ]; do 
-                  echo "Command still running..."
-                  sleep 10
-                done
-                aws ssm get-command-invocation --instance-id "$INSTANCE_ID" --command-id "${CMD_ID}" --query 'StatusDetails' --output text
-                aws ssm get-command-invocation --instance-id "$INSTANCE_ID" --command-id "${CMD_ID}" --query 'StandardOutputContent' --output text
+                if [[ "$INSTALL_K3S" == "true" ]]; then
+                  echo "Saving kubeconfig in Credential ${PROJECT}-${ENV}-kubeconfig"
+                  export INSTANCE_ID=$(cat tfstate/metadata | jq -r .instance_id)
+                  export AWS_ACCESS_KEY_ID=$(echo ${CY_AWS_CRED} | jq -r .access_key)
+                  export AWS_SECRET_ACCESS_KEY=$(echo ${CY_AWS_CRED} | jq -r .secret_key)
+                  export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
+                  export TERM=xterm
+                  aws ssm start-session --target ${INSTANCE_ID} \
+                  --document-name AmazonEKS-ExecuteNonInteractiveCommand \
+                  --parameters 'command="cat /home/admin/.kube/public_ip_config"' | tail -n +3 | head -n -3  >kubeconfig
+                  if ! cy credential create --name "${PROJECT}-${ENV}-kubeconfig" --canonical "${PROJECT}-${ENV}-kubeconfig" custom --field-file kubeconfig=kubeconfig; then
+                    echo "Error: cy returned code $?. Trying to update it."
+                    if ! cy credential update --name "${PROJECT}-${ENV}-kubeconfig" --canonical "${PROJECT}-${ENV}-kubeconfig" custom --field-file kubeconfig=kubeconfig; then
+                        echo "Error: cy returned code $?"
+                        exit 1
+                    fi
+                  fi
+                else
+                  echo "K3s not installed. Skipping..."
+                fi
 
-                CMD_ID=$(aws ssm send-command \
-                  --instance-ids "${INSTANCE_ID}" \
-                  --document-name 'AWS-RunShellScript' \
-                  --parameters 'commands=["cat /home/admin/.kube/public_ip_config"]' \
-                  --comment "Get Kube Config" | jq -r '.Command.CommandId')
-                until [ $(aws ssm get-command-invocation --instance-id "${INSTANCE_ID}" --command-id "${CMD_ID}" --query 'Status' --output text) != "InProgress" ]; do 
-                  echo "Command still running..."
-                  sleep 10
-                done
-                aws ssm get-command-invocation --instance-id "$INSTANCE_ID" --command-id "${CMD_ID}" --query 'StatusDetails' --output text
-                aws ssm get-command-invocation --instance-id "$INSTANCE_ID" --command-id "${CMD_ID}" --query 'StandardOutputContent' --output text
           inputs:
           - name: tfstate
             path: tfstate
         params:
           CY_AWS_CRED: '((aws_cred))'
           AWS_DEFAULT_REGION: '((aws_region))'
+          INSTALL_K3S: ((install_k3s))
 
       - task: run-cli-operations
         config:
@@ -208,10 +184,10 @@ jobs:
                 export AWS_SECRET_ACCESS_KEY=$(echo ${CY_AWS_CRED} | jq -r .secret_key)
                 export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
                 export TERM=xterm
-                if [[ "$vm_instance_status" = "Started" ]]; then
+                if [[ "$vm_instance_status" == "Started" ]]; then
                   echo "Starting instance ${instance_id}..."
                   aws ec2 start-instances --instance-ids ${instance_id}
-                elif [[ "$vm_instance_status" = "Stopped" ]]; then
+                elif [[ "$vm_instance_status" == "Stopped" ]]; then
                   echo "Stopping instance ${instance_id}..."
                   aws ec2 stop-instances --instance-ids ${instance_id}
                 fi
