small fix

diff --git a/stack-k3s-demo/pipeline/pipeline.yml b/stack-k3s-demo/pipeline/pipeline.yml
--- a/stack-k3s-demo/pipeline/pipeline.yml
+++ b/stack-k3s-demo/pipeline/pipeline.yml
@@ -32,6 +32,41 @@ jobs:
             chmod 600 ~/.ssh/git
             eval "$(ssh-agent -s)"
             ssh-add ~/.ssh/git
+            IPADDR=$(case $CLOUD_TYPE in
+              "Ionos") IPADDR=${IONOS_IP} ;;
+              "Outscale") IPADDR=${OUTSCALE_IP} ;;
+              "Other") IPADDR=${OTHER_IP} ;;
+              *) echo "IP Address not found" && exit 1 ;;
+            esac)
+            if ssh admin@${IPADDR} "ls"; then
+              USERNAME=admin
+            elif
+              if ssh root@${IPADDR} "ls"; then
+                USERNAME=root
+              elif
+                if ssh outscale@${IPADDR} "ls"; then
+                  USERNAME=outscale
+                elif
+                  echo "Error: SSH user not found... Tried [admin, root, outscale]"
+                  exit 1
+                fi
+              fi
+            fi
+            echo "Installing K3s..."
+            ssh ${USERNAME}@${IPADDR} "curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="server --disable traefik --disable servicelb --tls-san ${IPADDR}" sh -s -"
+            ssh ${USERNAME}@${IPADDR} "until sudo ls /etc/rancher/k3s/k3s.yaml /dev/null; do sleep 1; done"
+            ssh ${USERNAME}@${IPADDR} "mkdir -p ~/.kube && sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config && sudo chmod 644 ~/.kube/config"
+            ssh ${USERNAME}@${IPADDR} "export KUBECONFIG=~/.kube/config && kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.2/deploy/static/provider/cloud/deploy.yaml"
+            scp ${USERNAME}@${IPADDR}:~/.kube/config ~/kubeconfig
+            sed -i "s/127.0.0.1/${IPADDR}/" ~/kubeconfig
+            echo "Saving kubeconfig in Credential ${CY_ORG}-${PROJECT}-${ENV}-kubeconfig"
+            if ! cy credential create --name "${CY_ORG}-${PROJECT}-${ENV}-kubeconfig" --canonical "${CY_ORG}-${PROJECT}-${ENV}-kubeconfig" custom --field-file kubeconfig=~/kubeconfig; then
+              echo "Error: cy returned code $?. Trying to update it."
+              if ! cy credential update --name "${CY_ORG}-${PROJECT}-${ENV}-kubeconfig" --canonical "${CY_ORG}-${PROJECT}-${ENV}-kubeconfig" custom --field-file kubeconfig=~/kubeconfig; then
+                  echo "Error: cy returned code $?"
+                  exit 1
+              fi
+            fi
         params:
           SSH_PRIVATE_KEY: ((ssh_key))
           CLOUD_TYPE: ((cloud_type))
